name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: swift test -v

    - name: Build
      run: swift build -c release --arch arm64 --arch x86_64

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: ".build/apple/Products/Release/uBar"

    - uses: ncipollo/release-action@v1
      with:
        artifacts: ".build/apple/Products/Release/uBar"
